# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cef3ff23f0ba2e6e04fbec67a3487e5ffa14535ef2cc8ceecb57a6ac3dc968884efa2e889aa04888f6c601e2ecdb84160a74ce112ffbe9b7cf20186f088b484a

test:
  secret_key_base: 9a8cedd5bc5c0833d559d3b09e06bb7a9f37fda2f9158b92dc0706e87f2e4a876a47fa0c0df384ee015b3c32ff9785daabba208f3bee12e52a49bf578de61bb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
